services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: crypto_timescaledb
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: csabasallai
      POSTGRES_PASSWORD: passwordtest
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescale_data:
