services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: crypto_timescaledb
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: csabasallai
      POSTGRES_PASSWORD: passwordtest
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U csabasallai -d crypto_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 60s  

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: crypto_backend
    environment:
      DATABASE_URL: postgresql://csabasallai:passwordtest@timescaledb:5432/crypto_db
      COINGECKO_API_URL: https://api.coingecko.com/api/v3
      COLLECTION_INTERVAL: 50
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: on-failure 
   
  frontend:
    build: ./frontend
    container_name: crypto_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
   
volumes:
  timescale_data: